server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# Mybatis≈‰÷√
mybatis:
  mapperLocations: classpath*:config/mapper/**/*.xml
  config-locations: classpath*:config/mybatis/mybatis.xml
configuration:
  map-underscore-to-camel-case: true

#¥Ú”°»’÷æ
logging:
  level:
    com:
      ping:
        chen:
          mapper:
            debug